# Generated by Django 6.0.4 on 2026-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAPP', '0003_comment_created_at_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
